### DISCUSSION TITLE
A snippet for delegated tasks

### DISCUSSION THREAD

**Discussion by ironman820** [AnubisNekhet/AnuPpuccin#103] [Snippets]
I don't know SCSS enough to make a full pull request, but I added a new icon to a snippet to symbolize delegated tasks. I chose the "d" flag and adapted a segment of the compiled CSS from the final theme as a template to replace the icon with a person from Font Awesome.

`- [d] `

![Screenshot from 2023-03-04 10-27-02](https://user-images.githubusercontent.com/29488820/222917409-7a7d78c4-9d42-447c-a7bd-7f077567b746.png)

```css
.anp-custom-checkboxes [data-task='d'] input[type='checkbox']:checked,
.anp-custom-checkboxes [data-task='d'][type='checkbox']:checked {
  --checkbox-color: transparent;
  --checkbox-color-hover: transparent;
  border-width: 0;
}
.anp-custom-checkboxes [data-task='d'] input[type='checkbox']:checked:after,
.anp-custom-checkboxes [data-task='d'][type='checkbox']:checked:after {
  -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512'%3E%3C!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --%3E%3Cpath d='M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z'/%3E%3C/svg%3E");
  -webkit-mask-size: 100%;
  background-color: rgb(var(--ctp-blue));
  left: 0px;
}
.anp-custom-checkboxes [data-task='d'] input[type='checkbox']:checked:before,
.anp-custom-checkboxes [data-task='d'][type='checkbox']:checked:before {
  color: var(--checkbox-color);
  margin: 0 3px;
  position: absolute;
  left: calc(var(--checkbox-size) * 1);
  font-weight: bold;
}
```
