### DISCUSSION TITLE
Is there a way to see the entire filename of each note in the sidebar?

### DISCUSSION THREAD

**Discussion by carolinaqzx** [AnubisNekhet/AnuPpuccin#150] [Ideas]
Right now I can only see trimmed file names in the sidebar, so that each note takes up one line. However, it is important that I see the entire file name. Can I do this using CSS? I know this is an option in the minimal theme, but I much rather use AnuPpuccin :)

**Comment by subhinay** [comment]
This works for me:
```css
/* --- wrap titles in File Explorer --- */
.nav-file-title-content, .nav-folder-title-content {
    overflow: visible;
    word-wrap: break-word;
    white-space: pre-wrap;
}

```
