### DISCUSSION TITLE
Custom folder colors based on name

### DISCUSSION THREAD

**Discussion by AnubisNekhet** [AnubisNekhet/AnuPpuccin#18] [Snippets]
The following snippet allows you to set custom folder colors based on name instead of a simple repeating pattern (Works with both rainbow folder styles):
```css
.nav-folder:has(.nav-folder-title[data-path="00. Homepage"]) {
  --rainbow-folder-color: var(--ctp-green);
}
```
The only caveat is that it needs the latest obsidian version since it uses `:has()`.

**Comment by Gentleman03** [comment]
You can use this code if you're using older obsidian version. It's theme agnostic.

```css
.nav-folder-title[data-path="your folder name"] {
  color: #5999ff;
}
```
