### DISCUSSION TITLE
Custom Tags for Kanban cards (icons are macos only)

### DISCUSSION THREAD

**Discussion by pryley** [AnubisNekhet/AnuPpuccin#19] [Snippets]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/134939/210693078-b09195e8-813c-468e-97ec-811e44e16597.png">

```css
/* Custom Tags */

.kanban-plugin__item {
  --tag-opacity-bg: 0.18;
  --tag-opacity-border: 0.3;

  --tag-opacity-bg__hover-cyan: 0.28;
  --tag-opacity-bg__hover-green: 0.38;
  --tag-opacity-bg__hover-purple: 0.5;
  --tag-opacity-bg__hover-red: 0.38;
  --tag-opacity-bg__hover-yellow: 0.28;

  --tag-rgb__cyan: 160, 238, 238;
  --tag-rgb__green: 24, 224, 34;
  --tag-rgb__purple: 218, 207, 250;
  --tag-rgb__red: 254, 171, 171;
  --tag-rgb__yellow: 249, 242, 26;

  --tag-rgb-bg__cyan: 162, 238, 239;
  --tag-rgb-bg__green: 14, 138, 22;
  --tag-rgb-bg__purple: 83, 25, 231;
  --tag-rgb-bg__red: 252, 41, 41;
  --tag-rgb-bg__yellow: 250, 246, 27;
}

.kanban-plugin__item .kanban-plugin__item-tag[href="#bug"] {
  background-color: rgba(var(--tag-rgb-bg__red), var(--tag-opacity-bg));
  border: 1px solid rgba(var(--tag-rgb__red), var(--tag-opacity-bg));
  color: rgb(var(--tag-rgb__red));
  font-weight: 400;
}
.kanban-plugin__item .kanban-plugin__item-tag[href="#bug"]:hover {
  background-color: rgba(var(--tag-rgb-bg__red), var(--tag-opacity-bg__hover-red));
  border: 1px solid rgba(var(--tag-rgb__red), var(--tag-opacity-bg));
  text-decoration: none;
}
.kanban-plugin__item .kanban-plugin__item-tag[href="#compat"] {
  background-color: rgba(var(--tag-rgb-bg__purple), var(--tag-opacity-bg));
  border: 1px solid rgba(var(--tag-rgb__purple), var(--tag-opacity-bg));
  color: rgb(var(--tag-rgb__purple));
  font-weight: 400;
}
.kanban-plugin__item .kanban-plugin__item-tag[href="#compat"]:hover {
  background-color: rgba(var(--tag-rgb-bg__purple), var(--tag-opacity-bg__hover-purple));
  border: 1px solid rgba(var(--tag-rgb__purple), var(--tag-opacity-bg));
  text-decoration: none;
}
.kanban-plugin__item .kanban-plugin__item-tag[href="#fr"] {
  background-color: rgba(var(--tag-rgb-bg__cyan), var(--tag-opacity-bg));
  border: 1px solid rgba(var(--tag-rgb__cyan), var(--tag-opacity-bg));
  color: rgb(var(--tag-rgb__cyan));
  font-weight: 400;
}
.kanban-plugin__item .kanban-plugin__item-tag[href="#fr"]:hover {
  background-color: rgba(var(--tag-rgb-bg__cyan), var(--tag-opacity-bg__hover-cyan));
  border: 1px solid rgba(var(--tag-rgb__cyan), var(--tag-opacity-bg));
  text-decoration: none;
}
.kanban-plugin__item .kanban-plugin__item-tag[href="#new"] {
  background-color: rgba(var(--tag-rgb-bg__green), var(--tag-opacity-bg));
  border: 1px solid rgba(var(--tag-rgb__green), var(--tag-opacity-bg));
  color: rgb(var(--tag-rgb__green));
  font-weight: 400;
}
.kanban-plugin__item .kanban-plugin__item-tag[href="#new"]:hover {
  background-color: rgba(var(--tag-rgb-bg__green), var(--tag-opacity-bg__hover-green));
  border: 1px solid rgba(var(--tag-rgb__green), var(--tag-opacity-bg));
  text-decoration: none;
}
.kanban-plugin__item .kanban-plugin__item-tag[href="#test"] {
  background-color: rgba(var(--tag-rgb-bg__yellow), var(--tag-opacity-bg));
  border: 1px solid rgba(var(--tag-rgb__yellow), var(--tag-opacity-bg));
  color: rgb(var(--tag-rgb__yellow));
  font-weight: 400;
}
.kanban-plugin__item .kanban-plugin__item-tag[href="#test"]:hover {
  background-color: rgba(var(--tag-rgb-bg__yellow), var(--tag-opacity-bg__hover-yellow));
  border: 1px solid rgba(var(--tag-rgb__yellow), var(--tag-opacity-bg));
  text-decoration: none;
}

.mod-macos:not(.is-mobile) .kanban-plugin__item-tag {
  align-items: center;
  display: inline-flex;
}
.mod-macos:not(.is-mobile) .kanban-plugin__item-tag > span {
  display: none;
}
.mod-macos:not(.is-mobile) .kanban-plugin__item-tag::before {
  content:'􀆃';
  font-family: 'SF Pro';
  margin-left: -4px;
}
.mod-macos:not(.is-mobile) .kanban-plugin__item-tag[href="#bug"]::before {
  /* content:'􁕧'; */
  /* content:'􀌛'; */
  content:'􀍼';
  margin-right: 4px;
}
.mod-macos:not(.is-mobile) .kanban-plugin__item-tag[href="#compat"]::before {
  content:'􀋦';
  margin-right: 4px;
}
.mod-macos:not(.is-mobile) .kanban-plugin__item-tag[href="#fr"]::before {
  content:'􀨭';
  margin-right: 4px;
}
.mod-macos:not(.is-mobile) .kanban-plugin__item-tag[href="#important"]::before {
  color: red;
  content:'􀢒';
  margin-right: 4px;
}
.mod-macos:not(.is-mobile) .kanban-plugin__item-tag[href="#new"]::before {
  content:'􀆿';
  margin-right: 4px;
}
.mod-macos:not(.is-mobile) .kanban-plugin__item-tag[href="#test"]::before {
  content:'􀇿';
  margin-right: 4px;
}
```
