### DISCUSSION TITLE
Custom Accent Selector

### DISCUSSION THREAD

**Discussion by ms3056** [AnubisNekhet/AnuPpuccin#192] [Ideas]
I've added a custom accent color selector. 
The StyleSettings looks like this. I created a custom accent this way. 

```css
    -
        id: ctp-custom-color
        title: 'Select your preferred accent'
        type: variable-color
        default: '#'
        format: 'rgb-values'

     - 
        label: Custom Color
        value: ctp-accent-custom
        
 .anuppuccin-accent-toggle.ctp-accent-custom{
  --ctp-accent: var(--ctp-custom-color) !important;
}
```
You have to know what you are doing to enable this, that is why I made it an idea and not a snippet.
