### DISCUSSION TITLE
Custom file colors inherited from folder

### DISCUSSION THREAD

**Discussion by Tanjamuse** [AnubisNekhet/AnuPpuccin#193] [Snippets]
I unfortunately have no idea how to do this (or whether it's possible), but I would love a snippet to show how, if it's possible?

**Comment by AnubisNekhet** [comment]
```css
:root {
  --rainbow-file-opacity: 0.8;
}
.anp-simple-rainbow-color-toggle .nav-folder.mod-root .nav-folder-children .nav-folder .nav-file-title {
  color: rgba(var(--rainbow-folder-color), var(--rainbow-file-opacity));
}
```
