### DISCUSSION TITLE
[Help]: Cannot decrease the opacity of note tab?

### DISCUSSION THREAD

**Discussion by BaconCoding74** [AnubisNekhet/AnuPpuccin#240] [Ideas]
I'm new linux KDE user and I have no idea how to make the note tab translucent like the tab beside. I'm aware that I can decrease the opacity of my window but I just want to decrease the opacity of the note tab instead of whole window. Any suggestions? Thanks
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/152764368/7a9556f5-f50f-4508-b30c-326add2197aa)

**Comment by syrth-io** [comment]
I _think_ this snippet should do what you want!

```css
/* adjust note transparency */
.is-focused .workspace-leaf.mod-active .view-header, .workspace-leaf.mod-active .view-header, .workspace-leaf .view-header, .workspace-split.mod-root .view-content, .workspace-fake-target-overlay:not(.is-in-sidebar) .workspace-tabs .workspace-leaf, .workspace .mod-root .workspace-tabs.mod-stacked .workspace-tab-container .workspace-tab-header, .anp-card-layout .workspace .mod-root .workspace-tabs.mod-stacked .workspace-tab-container .workspace-leaf {
	background-color: rgb(var(--ctp-base), 0.5);
	--card-foreground-color: rgb(var(--ctp-base), 0.5);
	--card-background-color: rgb(var(--ctp-crust), 1); /* potentially needed for image backgrounds */
}

/* additional control for stacked tab headers to match note opacity */
.workspace .mod-root .workspace-tabs.mod-stacked .workspace-tab-container .workspace-tab-header {
	background-color: rgb(var(--ctp-base), 0.5);
}

/* remove faint gradient in header to avoid awkward color stop */
.mod-fade:not(.mod-at-end):after {
    background: transparent;
}
```

there's probably a more efficient or neater way to do the selectors, but that's what I've got for now lol. for the numbers at the end of the attributes (`0.5` and `1`), you can adjust them according to your desired transparency where `1` = 100% opaque and `0.5` = 50% opaque. this is what it looks like without the snippet:
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/f0c2e9b2-c575-4378-9c17-0548a4183a49)

without any changes to the snippet:
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/89c035f9-dbe9-42ac-9693-9f1bfc6fff00)
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/40762a4c-8841-4ee6-b8dd-d888072b982c)
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/b9b778ac-0136-4ddc-93bc-0cecac168ec3)

and without the additional tab header styling (note how it's more translucent than the note body--if you prefer this, just remove the corresponding section from the CSS):
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/89fdc583-7897-4946-b8ed-4539a0073d33)
![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/112804375/d2287618-a210-4836-8f0a-f9988a28e371)

I am not entirely sure if the `--card-background-color` property is needed or not as I'm just testing with the default colors and no background-image, but if you have trouble, try reducing the opacity there too.

it's not perfect, but I hope it helps! if you have any trouble, let me know. there's also a way to make the border inside less prominent if it bothers you, but I got a headache before I could play around with that, so also let me know if that's something you'd like.
