### DISCUSSION TITLE
Custom file colors based on tags

### DISCUSSION THREAD

**Discussion by AnubisNekhet** [AnubisNekhet/AnuPpuccin#27] [Snippets]
Requires supercharged links to be enabled.
```css
.nav-file-title {
  --custom-nav-item-color: rgb(var(--custom-nav-item-color-rgb));
  --custom-nav-item-color-hover: rgba(var(--custom-nav-item-color-rgb), 0.2);
  --nav-item-color: var(--custom-nav-item-color, var(--text-muted));
  --nav-item-color-hover: var(--custom-nav-item-color, var(--text-normal));
  --nav-item-color-active: var(--custom-nav-item-color, var(--text-normal));
  --nav-item-color-selected: var(--custom-nav-item-color, var(--text-normal));
  --nav-item-color-highlighted: var(--custom-nav-item-color, var(--text-accent-hover));
  --nav-item-background-hover: var(--custom-nav-item-color-hover, var(--background-modifier-hover));
  --nav-item-background-active: var(--custom-nav-item-color-hover, var(--background-modifier-hover));
  --nav-item-background-selected: var(--custom-nav-item-color-hover, rgba(var(--color-accent-hsl), 0.2));
}
.nav-file-title:has(.nav-file-title-content[data-link-tags*="#tag"]) {
  --custom-nav-item-color-rgb: var(--ctp-red);
}
```
