### DISCUSSION TITLE
Add file extension labels for .md files

### DISCUSSION THREAD

**Discussion by pryley** [AnubisNekhet/AnuPpuccin#30] [Snippets]
<img width="292" alt="image" src="https://user-images.githubusercontent.com/134939/211474462-4df475b8-86f0-4abd-8b9d-c53a683d91d2.png">

```css
.nav-file-title::after {
  align-self: center;
  background-color: var(--background-modifier-hover);
  border-radius: var(--radius-s);
  font-size: 9px;
  font-weight: var(--font-semibold);
  letter-spacing: 0.05em;
  line-height: var(--line-height-normal);
  margin-left: var(--size-2-3);
  padding: 0 var(--size-4-1);
  text-transform: uppercase;
}
.nav-file-title[data-path$=".md"]::after {
  content: 'md';
}
```
