### DISCUSSION TITLE
Center align canvas label text

### DISCUSSION THREAD

**Discussion by AnubisNekhet** [AnubisNekhet/AnuPpuccin#33] [Snippets]
```css
.canvas-node-content .h-center-text-canvas p {
  text-align: center;
}
.canvas-node-content .v-center-text-canvas div:nth-child(3) p {
  margin-block-start: 0;
}
.canvas-node-content .v-center-text-canvas div:last-child p {
  margin-block-end: 0;
}
.canvas-node-content.markdown-embed > .markdown-embed-content > .markdown-preview-view.v-center-text-canvas::before,
.canvas-node-content.markdown-embed > .markdown-embed-content > .markdown-preview-view.v-center-text-canvas::after {
  display: none;
}
.canvas-node-content.markdown-embed > .markdown-embed-content > .markdown-preview-view.v-center-text-canvas > .markdown-preview-sizer {
  flex: 0 0 0;
  margin-top: auto;
  margin-bottom: auto;
}
```
`h-center-text-canvas` aligns text horizontally and `v-center-text-canvas` aligns text vertically.
<img width="273" alt="image" src="https://user-images.githubusercontent.com/102488279/211981630-07abeb05-be90-4b0a-a31d-4ff6ab5912fb.png">
