### DISCUSSION TITLE
Adding a customizable indicator for lists, etc.

### DISCUSSION THREAD

**Discussion by brimwats** [AnubisNekhet/AnuPpuccin#52] [Snippets]
I use this prism list style snippet that I think would look good in anupip, but feel free to reject!

```css
/* ──────────────── Outliner ──────────────── */
.cm-hmd-list-indent .cm-tab {
	position: 					relative;
} 

.cm-hmd-list-indent .cm-tab::before {
	content: 					"";
	border-left: 				1px solid var(--base0);
	position:					absolute;
	left:						2px;
	top:						-9px;
	bottom:						-9999px;
} 

.cm-s-obsidian .HyperMD-list-line {
	padding-top: 				0em;
	position: 					relative;
	overflow: 					hidden;
}  

/* Adding a rule line before ul list -- EDITOR Mode  */

.markdown-source-view.mod-cm6.is-live-preview .HyperMD-list-line-1::after {
	content: 					'';
	border-left: 				.3em solid var(--text-accent);
	position: 					absolute;
	left: 						-0.1em;
	top: 						0em;
	bottom: 					0;
	height: 					100%;
	border-color:				#cc241d;
	clip-path: 					polygon(0% 0%, 75% 0%, 100% 50%, 75% 100%, 0% 100%);
} 

.HyperMD-list-line-2::after {
	content: 					'';
	border-left: 				.75em solid var(--text-accent);
	position: 					absolute;
	left: 						0em;
	top: 						0em;
	bottom: 					0;
	height: 					80%;
	border-color:				#fe8019;
	clip-path: 					polygon(0% 0%, 75% 0%, 100% 50%, 75% 100%, 0% 100%);
}

/* etc */
```
this is probably bad css bc I've had it forver, but use it how you like, I made it and it's cc0

here's an image of what it would look (ignore the line indicators, I had them on for something else)

![image](https://user-images.githubusercontent.com/49103046/214119638-a375b7fa-ea7e-4f3b-b9b7-56fd45118e25.png)
