### DISCUSSION TITLE
Custom Heading Color Gradients (Dark flavors only)

### DISCUSSION THREAD

**Discussion by pryley** [AnubisNekhet/AnuPpuccin#62] [Snippets]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/134939/215589829-f9e15bd6-b3ed-46d8-9cb0-3c3a2f824a24.png">

```css
.anp-header-color-toggle {
  --heading-gradient-color: rgb(var(--ctp-text));
}
.anp-header-color-toggle.theme-dark .HyperMD-header,
.anp-header-color-toggle.theme-dark .markdown-rendered :is(h1,h2,h3,h4,h5,h6) {
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-image: linear-gradient(0deg, rgb(var(--ctp-text)) 0%, var(--heading-gradient-color) 75%);
}
.HyperMD-header-1, .markdown-rendered h1 { --heading-gradient-color: var(--h1-color) }
.HyperMD-header-2, .markdown-rendered h2 { --heading-gradient-color: var(--h2-color) }
.HyperMD-header-3, .markdown-rendered h3 { --heading-gradient-color: var(--h3-color) }
.HyperMD-header-4, .markdown-rendered h4 { --heading-gradient-color: var(--h4-color) }
.HyperMD-header-5, .markdown-rendered h5 { --heading-gradient-color: var(--h5-color) }
.HyperMD-header-6, .markdown-rendered h6 { --heading-gradient-color: var(--h6-color) }
```

Make sure to also enable custom heading colors:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/134939/215590442-6942f5d9-5bf3-4ae7-b96a-503bff506d77.png">

**Comment by SteveDockar** [comment]
This is really clever! Is there a way to do something similar, and apply the effect, horizontally, to the header dividers?

**Reply by pryley** [reply]
Like this (add to the CSS code above):

```css
.anp-header-divider-color-toggle.theme-dark .HyperMD-header,
.anp-header-divider-color-toggle.theme-dark .markdown-rendered :is(h1,h2,h3,h4,h5,h6) {
    border-image-slice: 1;
    border-image-source: linear-gradient(to left, rgb(var(--ctp-text)) 0%, var(--heading-gradient-color) 75%);
}
```

**Reply by SteveDockar** [reply]
Thanks Paul, that's brilliant. I've just read the MDN docs for border-image-slice (which still confuses me) and border-image-source / linear gradient and thanks to your worked example, I have just what I was looking for! I decided I preferred the text in the solid heading colour but I've been able to incorporate the gradient divider. I'm still tinkering with length and fade positions, but wouldn't have been able to do it without your help, so thanks again!

Here's what I'm currently using for the divider:
``` css
.anp-header-divider-color-toggle.theme-dark .HyperMD-header,
.anp-header-divider-color-toggle.theme-dark .markdown-rendered :is(h1,h2,h3,h4,h5,h6) {
    border-image-slice: 1;
    /* border-image-source: linear-gradient(to left, rgb(var(--ctp-text)) 10%, var(--heading-gradient-color) 75%); */
    border-image-source: linear-gradient(to right, var(--heading-gradient-color) 0% , 50% , rgb(var(--ctp-base)) 80% );
}
```
I reversed the order while I was trying to understand the parameters. This now stays header coloured from 0% to 50% then fades out to the background colour at 80% of the width. 👍  

![image](https://github.com/AnubisNekhet/AnuPpuccin/assets/22272895/8d2a445d-a264-4b73-9b42-8912459fbea1)
