### DISCUSSION TITLE
Some fun accent colors to consider

### DISCUSSION THREAD

**Discussion by ms3056** [AnubisNekhet/AnuPpuccin#78] [Ideas]
I have added these colors via a hacked together snippet. The comment of the color is to allow my editor to display the color - for some reason most editors (all the editors I have tried) won't display the color when you define it as `--ctp-goldenrod: 178, 128, 7;`

```css
.theme-dark.anp-theme-ext-dark { 
    --ctp-confetti: 212, 206, 77;
    /* rgb(212, 206, 77) */
    --ctp-maize: 255, 203, 5;
    /* rgb(255, 203, 5) */
    --ctp-goldenrod: 178, 128, 7;
    /* rgb(178, 128, 7) */
    --ctp-emerald: 80, 200, 120;
    /* rgb(80, 200, 120) */
    --ctp-yellowgreen: 154, 205, 50;
    /* rgb(154, 205, 50) */
    --ctp-slime: 101,255,0;
    /* rgb(101,255,0) */
    --ctp-aliceblue: 240, 248, 255;
    /* rgb(240, 248, 255) */
    --ctp-coralblue: 205, 225, 244;
    /* rgb(205, 225, 244) */
    --ctp-lightsteelblue: 176, 196, 222;
    /* rgb(176, 196, 222) */
    --ctp-neonblue: 21,137,255; 
    /* rgb(21,137,255) */
    --ctp-steelblue: 70, 130, 180;
    /* rgb(70, 130, 180) */
    --ctp-cornflower: 100, 149, 237;
    /* rgb(100, 149, 237) */
    --ctp-denim: 22, 96, 178;
    /* rgb(22, 96, 178) */
    --ctp-slategray: 112, 128, 144;
    /* rgb(112, 128, 144) */
    --ctp-cement: 123, 139, 136;
    /* rgb(123, 139, 136) */
    --ctp-lilac: 200, 162, 200;
    /* rgb(200, 162, 200) */
    --ctp-orchid:218, 112, 214;
    /* rgb(218, 112, 214) */
    --ctp-rebeccapurple: 102, 51, 153;
    /* rgb(102, 51, 153) */
    --ctp-tapestry: 189, 113, 130;
    /* rgb(189, 113, 130) */
    --ctp-chocolate: 210, 105, 30;
    /* rgb(210, 105, 30) */
    --ctp-trinidad: 204, 79, 38;
    /* rgb(204, 79, 38) */
    --ctp-cinnabar: 213, 67, 56;
    /* rgb(213, 67, 56) */
    --ctp-tomato: 255, 99, 71;
    /* rgb(255, 99, 71) */
}
```

There is much more to this snippet to get it to work, I am just including this in case you want to use these colors in your snippets or if Anubis wants to consider some of them for the main theme.
