### DISCUSSION TITLE
Card Mode - add some color to the background

### DISCUSSION THREAD

**Discussion by ms3056** [AnubisNekhet/AnuPpuccin#79] [Snippets]
This snippet will add variations of color to the background in Card Layout. It uses the accent color with various opacities. 

```css
.theme-dark {
  --card-background-color: rgba(var(--ctp-accent), 0.01) !important;
  --card-foreground-color: rgba(var(--ctp-accent), 0.04) !important;
  --tab-outline-color: rgba(var(--ctp-accent), 0.4) !important;
}

/* the min/max/close buttons color */
div.titlebar-button-container.mod-right {
  background-color: rgba(var(--ctp-accent), 0.3) !important; 
}
```
