### ISSUE TITLE
[Feature Request] Remove Strikethrough for Checkboxes

### ISSUE THREAD

**Issue by arrowchan18** [AnubisNekhet/AnuPpuccin#118]
**Feature Description**
Add an option to remove strikethrough for checkboxes

**Miscellaneous Features**
Keeping the current style but simply remove the strikethrough

**Additional context**
![image](https://user-images.githubusercontent.com/126338989/224452525-864a1aa5-a295-43c0-ae60-6817a5d5ca75.png)
I love AnuPpuccin, really makes me obsess to Obsidian, adding a option here would be prefect (without custom checkbox)

**Comment by pryley** [comment]
Add this to a CSS snippet:

```css
:root {
    --checklist-done-decoration: none;
}
```

**Comment by arrowchan18** [comment]
Thank you so much Sir! I tried the CSS snippet but it seems not working on my end:
 
![Screenshot_1](https://user-images.githubusercontent.com/126338989/226769121-d1c62417-1de0-4d4a-b14f-ae55505a6497.png)

I tried both "Custom Checkboxes" enabled and disalbed, I want keep checkbox color and only remove the Strikethrough.

**Comment by pryley** [comment]
Then try this

```css
body {
    --checklist-done-decoration: none;
}
```
