### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by webdavis** [AnubisNekhet/AnuPpuccin#125]
**Feature Description**

Hello,

I would love the ability to adjust the line-width percentage for the page, the same way that Minimal theme offers.

I have attempted to use the following custom CSS snippet:

```css
body {
  --file-line-width: 88%;
}
```

However, this seems to only look reasonable in Editing mode. Once in Preview Mode, the lines are much too long. I don't know enough about the CSS styling mechanics of Obsidian to understand why there is such a big difference between Editing Mode and Preview Mode `--file-line-width` 🤷‍♂️.

I'm not sure if this is a reasonable request, but it's what I'm looking for, nonetheless.

**Additional context**

Here's a screenshot from Minimal Theme of what I am requesting (specifically the "Maximum line width %"):

<img width="561" alt="image" src="https://user-images.githubusercontent.com/23553256/225823831-07ca7ebd-1b8c-462f-a8c3-42d2884c203a.png">

**Comment by pryley** [comment]
Have you tried enabling the "Readable line length" setting in Obsidian?

<img width="925" alt="image" src="https://user-images.githubusercontent.com/134939/226777821-023b4898-eaaf-4f90-b3ec-d7b153d76ad3.png">

And if you want to adjust the readable line length, you can do this:

```css
body .is-readable-line-width {
  --file-line-width: 65ch; /* Change this value! */
}
body .is-readable-line-width .cm-content,
body .is-readable-line-width .cm-line {
  --file-line-width: 100%;
}
```
