### ISSUE TITLE
Small tab glitch when left sidebar is closed

### ISSUE THREAD

**Issue by inhji** [AnubisNekhet/AnuPpuccin#14]
When the sidebar is closed and the default tab setting is used, the left-most tab is positions slightly too far right to align with the rounded corner of the main container. This happens only if the Layout setting "Cards" is used.

![tabs_visual_bug](https://user-images.githubusercontent.com/322385/199323852-46005134-019d-4222-8447-af5d06c26df7.png)

I really appreciate you putting your theme out there, it is stunning <3

**Comment by inhji** [comment]
I'm using linux, specifically elementaryOS 6.1 which is based on Ubuntu 20.04.

**Comment by inhji** [comment]
Changing the padding from 15px to 25px fixes it:

```css
.mod-root .workspace-tab-header-container-inner {
    padding: 1px 25px 0;
}
```
