### ISSUE TITLE
[Feature Request] asymmetrical heading margins

### ISSUE THREAD

**Issue by mretier** [AnubisNekhet/AnuPpuccin#156]
Hi,
just tried out the template and really like it, especially the option to define heading margins.

Would it be possible to have asymmetrical margins? I'd like to larger spacing before and smaller after the heading.

Thanks =)

**Comment by AnubisNekhet** [comment]
Thanks for checking out the theme! Unfortunately, asymmetrical heading margins are a tad too specific with regards to general use-cases. I'd suggest using this snippet to achieve your goals:
```css
/* Change the values in :root as per your needs */
:root {
  --right-file-margin-width: 40%;
  --left-file-margin-width: 20%;
}
.anp-toggle-preview .markdown-preview-section {
  width: 100%;
  margin: 0 var(--right-file-margin-width) 0 var(--left-file-margin-width);
}
```
