### ISSUE TITLE
please add a function auto hide/reveal left ribbon bar when mouse leave/on[Feature Request] 

### ISSUE THREAD

**Issue by srun007** [AnubisNekhet/AnuPpuccin#229]
**Feature Description**
please add a function auto hide/reveal left ribbon bar when mouse leave/on

**Miscellaneous Features**
![Snipaste_2023-10-24_22-22-20](https://github.com/AnubisNekhet/AnuPpuccin/assets/80263694/3cf69779-fe64-485d-80e4-bdb477a90f65)

**Additional context**
i like your theme very much

**Comment by srun007** [comment]
left ribbon toolbar Hide to the left retention drawer

**Comment by syrth-io** [comment]
you can achieve this easily with a CSS snippet. this is what I use, though you may need to adjust the width or other options depending on your theme settings/personal taste. however, please leave credit intact, as I adapted this code from @Akifyss's [Border](https://github.com/Akifyss/obsidian-border) theme.

```css
/* 
    autohide ribbon (from Border theme) 
    https://github.com/Akifyss/obsidian-border
*/
body:not(.is-mobile) .workspace-ribbon.side-dock-ribbon.mod-left {
    --ribbon-width: 10px; transition: all var(--anim-duration-slow); }
body:not(.is-mobile) .workspace-ribbon.side-dock-ribbon.mod-left:hover {
    --ribbon-width: 44px; transition: all var(--anim-duration-slow); }

body:not(.is-mobile) .workspace-ribbon.side-dock-ribbon.mod-left>* {
    opacity: 0; transition: all var(--anim-duration-slow); }
body:not(.is-mobile) .workspace-ribbon.side-dock-ribbon.mod-left:hover>* {
    opacity: 1; transition: all var(--anim-duration-slow); }
```
