### ISSUE TITLE
[Bug] how to change the color of backlinks and outgoing links?

### ISSUE THREAD

**Issue by fvnky07** [AnubisNekhet/AnuPpuccin#285]
I have been looking in the settings everywhere for an option to change the color for backlinks as at the moment they are indistinguishable from any other text. can you provide a snippet for me to change their font color?

**Comment by domizianooo** [comment]
You can write this css snippet:
```css
/* For edit mode */
.cm-hmd-internal-link {
    color: blue !important;
}

/* For visual mode */
.internal-link {
    color: blue !important;
}
```

Of course choosing whatever color you like
