### ISSUE TITLE
[Feature Request] Some CSS I use with this theme to make it cleaner and more to my taste, might want to add some as options in Style Settings?

### ISSUE THREAD

**Issue by firinael** [AnubisNekhet/AnuPpuccin#3]
Code below (warning, some of it may be janky)! I use these in a lot of themes just to make them look softer, flatter, and just generally nicer to look at. You might want to add some of them as options to Style Settings! The code that's been taken from somewhere is clearly demarcated btw.

Also something that'd look super cool with this theme is this gradient used in [cairo401's Royal Velvet theme](https://github.com/caro401/royal-velvet/issues/13)!

![image](https://user-images.githubusercontent.com/67032657/204050023-7dc88790-3cd2-41df-a0f8-7479a7547207.png)

```css
body {
    --heading-font                    : "Lexend Deca Semibold";
    --font-monospace                  : "JetBrains Mono";
    --font-text                       : "iA Writer Quattro S";
    --font-interface                  : "Lexend Deca";
    --table-header-font               : var(--heading-font);
    --background-modifier-border-hover: transparent !important;
    --modal-border-color              : transparent !important;
    --prompt-border-color             : transparent !important;
    --background-modifier-border-focus: transparent !important;
    --background-modifier-boder       : transparent !important;
    --default-font                    : "Lexend Deca";
    --input-shadow                    : none !important;
    --blockquote-border-color         : none;
    --divider-color                   : transparent;
    --indentation-guide-color         : var(--bold-color);
    --indentation-guide-color-active  : var(--italic-color);
    --text-highlight-bg               : #0000007F !important;
}

.kanban-plugin__lane,
.kanban-plugin__item {
    border-color: transparent !important;
}

.cm-active.cm-line {
    background-color: rgba(0, 0, 0, 0.1);
}

.checkbox-container {
    background-color: var(--color-base-00);
}

.block-language-simple-time-tracker,
.callout-title-inner,
.kanban-plugin__lane-title-text p {
    font-family: var(--font-interface);
}

.markdown-preview-sizer {
    padding-bottom: 0 !important;
    min-height    : fit-content !important;
}

.setting-item-control *:not(input[type="text"],
    input[type="search"],
    input[type="email"],
    input[type="password"],
    input[type="number"]),
.clickable-icon {
    cursor: pointer !important;
}

button {
    font-family: var(--font-interface) !important;
    cursor     : pointer !important;
}

.explorable {
    padding-right: 4px !important;
    padding-left : 4px !important;
}

img {
    display      : block !important;
    margin-left  : auto !important;
    margin-right : auto !important;
    margin-top   : 20px !important;
    margin-bottom: 20px !important;
    border-radius: var(--radius-s);
}

.markdown-preview-view .math.math-block mjx-container mjx-math.MJX-TEX {
    padding-top   : 14px;
    padding-bottom: 14px;
}

.cm-formatting-quote {
    color: var(--text-muted) !important;
}

mjx-container.MathJax {
    -webkit-text-fill-color: var(--text-normal);
}

.MJX-TEX {
    font-size: 1.2em !important;
}

em,
.cm-em {
    font-family: var(--font-text) !important;
}

mjx-mtable>*>mjx-itable mjx-mtr:not(:first-of-type) mjx-mtd {
    padding-top: 1.2em !important;
}

.HyperMD-header,
.markdown-preview-view :is(h1, h2, h3, h4, h5, h6) {
    font-family: var(--heading-font);
}

.cm-blockid,
.titlebar-text {
    opacity: 0;
}

.cm-active .cm-blockid,
.cm-blockid:hover {
    opacity: 1;
}

.workspace-ribbon.mod-left,
.sidebar-toggle-button.mod-right,
.status-bar,
.frontmatter-container,
.workspace-leaf-content[data-type=kanban]>.view-header,
.kanban-plugin__lane-header-wrapper:not(:hover) .kanban-plugin__lane-settings-button-wrapper,
.kanban-plugin__item-title-wrapper:not(:hover) .kanban-plugin__item-postfix-button-wrapper {
    display: none;
}

.workspace-tab-header:not(:hover) .workspace-tab-header-inner-close-button,
.workspace-tab-header-container:not(:hover) .clickable-icon,
.kanban-plugin__lane-header-wrapper:not(:hover) .kanban-plugin__lane-grip {
    visibility: hidden;
}

.titlebar-button.mod-close:hover {
    color: black;
}

.theme-dark.theme-dark {
    --text-normal: #fafafa;
}

.theme-light.theme-light {
    --text-normal: black;
}

.cm-s-obsidian .external-link {
    background-image: none !important;
    padding-right   : 0px !important;
}

/* pseudometa */
/* Image Alt as caption
(except when no explicit alt is provided and urls are the alt text) */
body:not(.no-image-alttext-caption) .image-embed[alt]:not([alt$=".png"], [alt$=".jpg"], [alt$=".jpeg"], [alt$=".tiff"])::after {
    display: block;
    content: attr(alt);

    font-family: var(--font-text);
    font-size  : var(--font-smaller);
    font-style : italic;

    color: var(--text-muted);

    word-spacing: -3px;

    margin-top   : -1em;
    margin-bottom: 1em;
}

.markdown-preview-view img[src] {
    border       : var(--thin-muted-border);
    border-radius: var(--radius-s);
}

/* centers image and image caption */
.image-embed[alt]::after {
    text-align: center;
}

.view-content img {
    display     : block;
    margin-right: auto;
    margin-left : auto;
}

/* ───────────────────────────────────────────────── */
/* << Overlaying Sidebar
──────────────────────────────────────────────────── */

.mod-right-split {
    position: absolute;
    right   : 0;
}
```
