### ISSUE TITLE
[Bug] Live Preview Editor Font isn't being used

### ISSUE THREAD

**Issue by LucasOe** [AnubisNekhet/AnuPpuccin#349]
**Describe the bug**
The font set in the "Live Preview Editor Font" setting in the Style Settings plugin isn't being applied. Instead, the font uses the system's default font as a fallback.

**To Reproduce**
1. Open Style Settings and set a font in "Live Preview Editor Font"
2. Open a note in live mode
3. The font isn't being used

I have observed this behavior using Obsidian version 1.9.1 and without CSS snippets.

**Comment by LucasOe** [comment]
https://github.com/AnubisNekhet/AnuPpuccin/blob/82d207c646904e7af371ced499f682fbdfad1012/src/modules/Base/editor.scss#L43C1-L45C2

This line should be:
```css
.markdown-live-view {
    --font-text: var(--anp-editor-font-lp, var(--font-text-override)), var(--font-text-theme), var(--font-interface);
}
```
