### ISSUE TITLE
[Feature Request] Theme variable transparency support

### ISSUE THREAD

**Issue by ms3056** [AnubisNekhet/AnuPpuccin#35]
I would like to color the background in card mode to `rgba(var(--ctp-accent), 0.3); `but for some reason this doesn't work. I admit to now knowing why - I just know that the rgba tag works with some colors but not this one for whatever reason. 

Do the current variables support this or is there something special about how this variable is being used that it would take effort to support it? 

Thanks!

**Comment by AnubisNekhet** [comment]
Hi, could you send the css you're using? I can try to help if I can see what's exactly being done.

**Comment by ms3056** [comment]
Sure - here ya go. If I make `--ctp-crust: var(--ctp-accent); `it works fine but the color is too bright. I would like a muted version of --ctp-accent with which I have created a way to custom select more colors. 

```css
.theme-dark.anp-theme-ext-dark.ctp-monokai-dark {
  --ctp-subtext0: 255, 138, 96; /* Settings Headers */
/* color: rgb(5, 78, 166) */
  --ctp-overlay2: 60, 96, 158; /* dark calendar text */
/* color: rgb(60, 96, 158) */
  --ctp-overlay1: 7, 50, 148;
/* color: rgb(7, 50, 148) */
  --ctp-overlay0: 9, 37, 140;
/* color: rgb(9, 37, 140) */
  --ctp-surface2: 220, 75, 5;
/* color: rgb(220, 75, 5) */
  --ctp-red: 235, 203, 139; /* filename */
/* color: rgb(235, 203, 139) */
  --ctp-text: 130, 159, 220; /* main text */
/* color: rgb(130, 159, 220) */
  --ctp-overlay2: 252, 152, 103; /* dark calendar text */
/* color: rgb(252, 152, 103) */
  --ctp-base: 34, 31, 34; /* main background */
/* color: rgb(34, 31, 34) */
  --ctp-mantle: 45, 42, 46; /* sidebar background */
/* color: rgb(45, 42, 46) */
  --ctp-crust: rgba(var(--ctp-accent), 0.6); /* shadows, popups and top bar */
/* color: rgb(45, 42, 46) */
}
```
