### ISSUE TITLE
[Feature Request] Use the Obsidian folder icons?

### ISSUE THREAD

**Issue by pryley** [AnubisNekhet/AnuPpuccin#5]
You could use the built-in Obsidian [folder icons](https://lucide.dev/?search=folder) instead of Bootstrap icons (unless you prefer those). Here is the CSS I use to override the icons:

```css
body.anp-collapse-folders .nav-folder:not(.is-collapsed) .nav-folder-collapse-indicator {
    -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m6 14 1.45-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.55 6a2 2 0 0 1-1.94 1.5H4a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h3.93a2 2 0 0 1 1.66.9l.82 1.2a2 2 0 0 0 1.66.9H18a2 2 0 0 1 2 2v2'/%3E%3C/svg%3E") !important;
    width: 16px;
    height: 16px;
    margin-top: 0px;
    margin-right: 5px;
    margin-left: 0px;
}
body.anp-collapse-folders .nav-folder.is-collapsed .nav-folder-collapse-indicator {
    -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.93a2 2 0 0 1-1.66-.9l-.82-1.2A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2Z'/%3E%3Cpath d='M2 10h20'/%3E%3C/svg%3E%0A") !important;
    width: 16px;
    height: 16px;
    margin-top: 0px;
    margin-right: 5px;
    margin-left: 0px;
}
```

<img width="306" alt="image" src="https://user-images.githubusercontent.com/134939/208345406-8625e708-74c0-4e36-86cf-ebbf13ac7b00.png">

**Alternative version** (folder-open is visually the same width):

```css
body.anp-collapse-folders .nav-folder:not(.is-collapsed) .nav-folder-collapse-indicator {
    -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 27 24' fill='none' stroke='currentColor' stroke-linejoin='round' stroke-linecap='round' stroke-width='2'%3E%3Cpath d='M6 14l1.45-2.9A2 2 0 0 1 9.24 10H22a2 2 0 0 1 1.94 2.5l-1.55 6a2 2 0 0 1-1.94 1.5H4a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2h3.93a2 2 0 0 1 1.66.9l.82 1.2a2 2 0 0 0 1.66.9H20a2 2 0 0 1 2 2v2'/%3E%3C/svg%3E%0A");
    width: 17px;
    height: 16px;
    margin-top: 0px;
    margin-right: 4px;
    margin-left: 0px;
}
body.anp-collapse-folders .nav-folder.is-collapsed .nav-folder-collapse-indicator {
    -webkit-mask-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 27 24' fill='none' stroke='currentColor' stroke-linejoin='round' stroke-linecap='round' stroke-width='2'%3E%3Cpath d='M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.93a2 2 0 0 1-1.66-.9l-.82-1.2A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2z'/%3E%3Cpath d='M2 10h20' /%3E%3C/svg%3E%0A");
    width: 17px;
    height: 16px;
    margin-top: 0px;
    margin-right: 4px;
    margin-left: 0px;
}
```

<img width="306" alt="image" src="https://user-images.githubusercontent.com/134939/208349679-23984906-72d6-4814-bbee-6b0a56f18488.png">
