### ISSUE TITLE
[Feature Request] Prism or other list styles?

### ISSUE THREAD

**Issue by brimwats** [AnubisNekhet/AnuPpuccin#51]
I use this prism list style snippet that I think would look good in anupip, but feel free to reject!

```css
/* ──────────────── Outliner ──────────────── */
.cm-hmd-list-indent .cm-tab {
	position: 					relative;
} 

.cm-hmd-list-indent .cm-tab::before {
	content: 					"";
	border-left: 				1px solid var(--base0);
	position:					absolute;
	left:						2px;
	top:						-9px;
	bottom:						-9999px;
} 

.cm-s-obsidian .HyperMD-list-line {
	padding-top: 				0em;
	position: 					relative;
	overflow: 					hidden;
}  

/* Adding a rule line before ul list -- EDITOR Mode  */

.markdown-source-view.mod-cm6.is-live-preview .HyperMD-list-line-1::after {
	content: 					'';
	border-left: 				.3em solid var(--text-accent);
	position: 					absolute;
	left: 						-0.1em;
	top: 						0em;
	bottom: 					0;
	height: 					100%;
	border-color:				#cc241d;
	clip-path: 					polygon(0% 0%, 75% 0%, 100% 50%, 75% 100%, 0% 100%);
} 

.HyperMD-list-line-2::after {
	content: 					'';
	border-left: 				.75em solid var(--text-accent);
	position: 					absolute;
	left: 						0em;
	top: 						0em;
	bottom: 					0;
	height: 					80%;
	border-color:				#fe8019;
	clip-path: 					polygon(0% 0%, 75% 0%, 100% 50%, 75% 100%, 0% 100%);
}

/* etc */
```
