### ISSUE TITLE
[Feature Request] LaTeX styling

### ISSUE THREAD

**Issue by ghost** [AnubisNekhet/AnuPpuccin#55]
I think it would be great if there was an option for colorful inline LaTeX to make it stand out more, sort of like there is color for italic and bold text. It would also be awesome if displayed formulas could have an outline around them, maybe like if they were inside callouts.

Thanks for an amazing theme!

**Comment by pryley** [comment]
@bastianlervik Do you have any examples?

**Comment by pryley** [comment]
Is this the kind of thing you are looking for?

### Display an outline around a LaTex block when hovering the cursor over it:

```css
.theme-dark .math-block,
.theme-light .math-block {
  --embed-block-shadow-hover: 0 0 0 1px var(--background-modifier-border), inset 0 0 0 1px var(--background-modifier-border);
}
```

<img width="710" alt="image" src="https://user-images.githubusercontent.com/134939/215306073-95bb2c77-633e-40e7-87b2-3d2fff156336.png">

### Apply the accent color to _inline_ LaTex:

```css
.math:not(.math-block) {
  color: var(--color-accent);
}
```

<img width="785" alt="image" src="https://user-images.githubusercontent.com/134939/215305982-7859c84d-4ae5-403d-b1cb-816791b35ce2.png">

### Display a LaTex block inside a callout (no CSS needed!):

<img width="695" alt="image" src="https://user-images.githubusercontent.com/134939/215305632-6626e681-2836-4254-94af-89a9a28e3520.png">

**Comment by AnubisNekhet** [comment]
There is an inbuilt formula callout which may help you with the latter:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/102488279/215328650-ea30e172-ad92-4481-8023-cdd9fa21a73e.png">
<img width="378" alt="image" src="https://user-images.githubusercontent.com/102488279/215328657-63dcf6a4-e396-49db-b121-cca4df15424c.png">

**Comment by AnubisNekhet** [comment]
Obsidian's CSS also overrides LaTeX colors (which is weird) so I'll be removing that to show proper LaTeX styling.
<img width="357" alt="image" src="https://user-images.githubusercontent.com/102488279/215328711-f1d49483-b2d7-4830-b659-036417e7e7d1.png">

**Comment by ghost** [comment]
I wasn’t aware of the formula callout. Is it possible to make it fill the entire line width like other callouts? It’s a tiny issue, but it would make it perfect. It’s awesome regardless, thanks a lot! And the snippet from pryley, which applies the accent color to inline LaTeX is also exactly what i was looking for. Thank you!

**Comment by pryley** [comment]
> Is it possible to make it fill the entire line width like other callouts?

```css
.callout[data-callout=formula] {
    width: auto;
}
```

<img width="845" alt="image" src="https://user-images.githubusercontent.com/134939/215343606-317a2978-58a2-43aa-b4b3-d5620c7f528f.png">
